version: "3.0"
  
services:
  tor:
    image: bavuongco10/docker-tor-proxy:us
    container_name: docker-tor-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9050:9050
      - 9051:9051
      - 8118:8118
    restart: always
